--Kiểm tra password > 8 kí tự
ALTER TABLE ACCOUNT  ADD CONSTRAINT CHK_PASSWORD CHECK (LEN(PASSWORD) >8)

-- Kiểm tra loại tài khoản trong 3 laoij
ALTER TABLE ACCOUNT  ADD CONSTRAINT CHK_USER_TYPE CHECK (USER_TYPE IN ('ADMIN','RECRUITER','CANDIDATE'))
--Kiểm tra email duy nhất 
ALTER TABLE ACCOUNT ADD UNIQUE(EMAIL)
--Tên lớn hơn 4 kí tự
ALTER TABLE ADMIN  ADD CONSTRAINT CHK_AD_NAME CHECK (LEN(ADMIN_NAME) >4)

--Tuổi admin lớn hơn 18
ALTER TABLE ADMIN  ADD CONSTRAINT CHK_AD_DOB CHECK (datediff(year,Date_Of_Birth,GETDATE())>18)
--Số điện thoại >= 10 chữ số
ALTER TABLE ADMIN  ADD CONSTRAINT CHK_AD_PHONE_NUMBER CHECK (LEN(PHONE_NUMBER) >=10)
--Email duy nhất
ALTER TABLE ADMIN ADD UNIQUE(EMAIL)
--Ngày tạo không lớn hơn ngày hôm nay
ALTER TABLE ADMIN  ADD CONSTRAINT CHK_AD_CREATED_DATE CHECK (datediff(year,CREATED_DATE,GETDATE())>=0)
--Tên lớn hơn 4 kí tự
ALTER TABLE CANDIDATE  ADD CONSTRAINT CHK_CANDIDATE_NAME CHECK (LEN(CANDIDATE_NAME) >4)
--Tuổi lớn hơn 18
ALTER TABLE CANDIDATE  ADD CONSTRAINT CHK_CANDIDATE_DOB CHECK (datediff(year,Date_Of_Birth,GETDATE())>18)
--Số đt ít nhất 10 số
ALTER TABLE CANDIDATE  ADD CONSTRAINT CHK_CANDIDATE_PHONE_NUMBER CHECK (LEN(PHONE_NUMBER) >=10)
--Email duy nhất
ALTER TABLE CANDIDATE ADD UNIQUE(EMAIL)
--Ngày tạo trước ngày hôm nay
ALTER TABLE CANDIDATE  ADD CONSTRAINT CHK_CANDIDATE_CREATED_DATE CHECK (datediff(year,CREATED_DATE,GETDATE())>=0)
